version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - ${ServerPort}:${ServerPort}
      - 2345:2345 #delve debug normal
      - 4000:4000 #delve debug tests
    volumes:
      - .:/clean_web
    env_file: .env
    depends_on:
      - database

  database:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${DBUsername}
      POSTGRES_PASSWORD: ${DBPassword}
      POSTGRES_DATABASE: ${DBName}
    volumes:
      - psql_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - ${AdminerPort}:8080
    depends_on:
      - database


volumes:
  psql_data:
    external: true
    name: psql_data
